version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - GIT_NAME=${GIT_NAME}
        - GIT_EMAIL=${GIT_EMAIL}
        - GIT_SSH_PRIVATE_KEY=${GIT_SSH_PRIVATE_KEY}
    platform: linux/amd64
    restart: on-failure
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    tty: true
